//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trang_chu_Main_Page_.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trang_chu_Main_Page_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_ht {
            get {
                object obj = ResourceManager.GetObject("1 ht", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45292 {
            get {
                object obj = ResourceManager.GetObject("45292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _452921 {
            get {
                object obj = ResourceManager.GetObject("452921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_coloured_background_with_variety_transparent_raindrops {
            get {
                object obj = ResourceManager.GetObject("abstract-coloured-background-with-variety-transparent-raindrops", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_coloured_background_with_variety_transparent_raindrops1 {
            get {
                object obj = ResourceManager.GetObject("abstract-coloured-background-with-variety-transparent-raindrops1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_coloured_background_with_variety_transparent_raindrops2 {
            get {
                object obj = ResourceManager.GetObject("abstract-coloured-background-with-variety-transparent-raindrops2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Icon {
            get {
                object obj = ResourceManager.GetObject("Exit_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Icon1 {
            get {
                object obj = ResourceManager.GetObject("Exit_Icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freepik__an_abstract_background_with_a_gradient_of_colors_s__56418 {
            get {
                object obj = ResourceManager.GetObject("freepik__an-abstract-background-with-a-gradient-of-colors-s__56418", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freepik__an_abstract_background_with_a_gradient_of_colors_s__564181 {
            get {
                object obj = ResourceManager.GetObject("freepik__an-abstract-background-with-a-gradient-of-colors-s__564181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_6667 {
            get {
                object obj = ResourceManager.GetObject("IMG_6667", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isolated_soap_oil_bubbles_watery_background {
            get {
                object obj = ResourceManager.GetObject("isolated-soap-oil-bubbles-watery-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap isolated_soap_oil_bubbles_watery_background1 {
            get {
                object obj = ResourceManager.GetObject("isolated-soap-oil-bubbles-watery-background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_941871524_1024x1024 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-941871524-1024x1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_941871524_1024x10241 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-941871524-1024x10241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log_Bù_Công {
            get {
                object obj = ResourceManager.GetObject("Log Bù Công", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_nhân_viên_hover {
            get {
                object obj = ResourceManager.GetObject("logo nhân viên hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_nhân_viên_hover1 {
            get {
                object obj = ResourceManager.GetObject("logo nhân viên hover1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_nhân_viên_hover2 {
            get {
                object obj = ResourceManager.GetObject("logo nhân viên hover2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_nhân_viên_hover3 {
            get {
                object obj = ResourceManager.GetObject("logo nhân viên hover3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_nhân_viên_hover4 {
            get {
                object obj = ResourceManager.GetObject("logo nhân viên hover4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Red_Abstract_Background_Instagram_Post__17_ {
            get {
                object obj = ResourceManager.GetObject("Red Abstract Background Instagram Post (17)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roiii {
            get {
                object obj = ResourceManager.GetObject("roiii", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_02_25_232956 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-02-25 232956", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_02_25_233149 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-02-25 233149", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_02_28_180709 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-02-28 180709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_02_28_1807091 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-02-28 1807091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2025_02_28_182032 {
            get {
                object obj = ResourceManager.GetObject("Screenshot 2025-02-28 182032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_2 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_3 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_4 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__1_5 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (1)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__10_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__11_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (11)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__12_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__13_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (13)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__13_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (13)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__14_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (14)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__15_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (15)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__15_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (15)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__16_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (16)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_2 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_3 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_4 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__2_5 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (2)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__3_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__3_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (3)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__3_2 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (3)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__4_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__4_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (4)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__5_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__5_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__5_2 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (5)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__6_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__6_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (6)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__7_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (7)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__7_1 {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (7)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__8_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (8)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thiết_kế_chưa_có_tên__9_ {
            get {
                object obj = ResourceManager.GetObject("Thiết kế chưa có tên (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z6337298354173_6e29e312c0f5bb2790c6e3e14bd06be8 {
            get {
                object obj = ResourceManager.GetObject("z6337298354173_6e29e312c0f5bb2790c6e3e14bd06be8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
